name: Releases

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true

      - name: Install latest build tools
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;33.0.1" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.1.8937393" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
          gradle-home-cache-cleanup: true

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            app/build/outputs/apk/release/app-release.apk
